# Render.com deployment configuration for PluggedAF Admin Panel

services:
  - type: web
    name: pluggedaf-admin-panel
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false  # Set this manually in Render dashboard
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false  # Set this manually in Render dashboard
      - key: BACKEND_API_URL
        value: https://pluggedaf-auth-api.onrender.com
      - key: JWT_SECRET
        sync: false  # Set this manually in Render dashboard
      - key: FRONTEND_URL
        value: https://your-frontend-domain.vercel.app
    healthCheckPath: /
    
# Alternative deployment options:

# For Vercel deployment:
# 1. Install Vercel CLI: npm i -g vercel
# 2. Run: vercel --prod
# 3. Set environment variables in Vercel dashboard

# For Netlify deployment:
# 1. Build command: npm install
# 2. Publish directory: ./
# 3. Set environment variables in Netlify dashboard

# For Heroku deployment:
# 1. Create Procfile: web: npm start
# 2. Set environment variables using: heroku config:set KEY=value
